
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY , SUM(c.SALES * b.PRICE )AS TOTAL_SALES
FROM BOOK as b JOIN AUTHOR as a
ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES as c 
ON c.BOOK_ID = b.BOOK_ID
WHERE c.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME , b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC