SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE as f 
LEFT JOIN USED_GOODS_BOARD as t
ON f.BOARD_ID = t.BOARD_ID
WHERE t.VIEWS = (SELECT MAX(b.VIEWS) FROM USED_GOODS_BOARD as b)
ORDER BY f.FILE_ID DESC